### ISSUE TITLE
opt parse applicative minor API change

### ISSUE THREAD

**Issue by ghost** [danchoi/yahooQuote#1]
https://github.com/pcapriotti/optparse-applicative/blob/master/CHANGELOG.md#version-0100-1-sep-2014

option now takes in an extra parameter. I would also set a version range on this package in the cabal file.

**Comment by danchoi** [comment]
This repo is deprecated. Please continue development at https://github.com/MackeyRMS/yahooQuote

**Comment by ghost** [comment]
Sure, just letting you know if you were still maintaining this.
